# Generated by Django 5.1.4 on 2025-01-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='model',
            field=models.CharField(choices=[('1BHK', 'One Bedroom'), ('2BHK', 'Two Bedroom'), ('3BHK', 'Three Bedroom'), ('FULL', 'Full House'), ('AIRBNB', 'Airbnb')], max_length=10),
        ),
    ]
