# Generated by Django 5.1.5 on 2025-07-18 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_house_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the landlord', max_length=255)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(help_text='Email address for communication', max_length=254, unique=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the landlord', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the landlord is active')),
            ],
            options={
                'verbose_name': 'Landlord',
                'verbose_name_plural': 'Landlords',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['name'], 'verbose_name': 'House', 'verbose_name_plural': 'Houses'},
        ),
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=models.TextField(blank=True, help_text='List of amenities (comma-separated)', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1, help_text='Number of bathrooms'),
        ),
        migrations.AddField(
            model_name='house',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1, help_text='Number of bedrooms'),
        ),
        migrations.AddField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, help_text='Additional property description', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_meter_number',
            field=models.CharField(blank=True, help_text='Electricity meter number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the property is active for rent'),
        ),
        migrations.AddField(
            model_name='house',
            name='name',
            field=models.CharField(default='Unnamed Property', help_text='Name/identifier of the property', max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='square_footage',
            field=models.PositiveIntegerField(blank=True, help_text='Square footage of the property', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='house',
            name='water_meter_number',
            field=models.CharField(blank=True, help_text='Water meter number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_occupied',
            field=models.BooleanField(default=False, help_text='Whether the property is currently occupied'),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(help_text='Physical location/address', max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='model',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('mansion', 'Mansion'), ('studio', 'Studio'), ('duplex', 'Duplex'), ('townhouse', 'Townhouse'), ('single_room', 'Single Room'), ('double_room', 'Double Room')], default='apartment', help_text="Type of property (kept as 'model' for backward compatibility)", max_length=30),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.PositiveIntegerField(help_text='Monthly rental price in UGX'),
        ),
        migrations.AddField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(blank=True, help_text='Owner of the property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to='houses.landlord'),
        ),
    ]
