# Generated by Django 5.1.5 on 2025-07-19 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_landlord_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+256705672545'. Up to 13 digits allowed.", regex='^\\+256\\d{9}$')]),
        ),
    ]
