# Generated by Django 5.1.5 on 2025-07-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_alter_landlord_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='electricity_meter_number',
        ),
        migrations.RemoveField(
            model_name='house',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='house',
            name='model',
            field=models.CharField(choices=[('1BHK', '1 Bedroom Hall Kitchen'), ('2BHK', '2 Bedroom Hall Kitchen'), ('Studio', 'Studio'), ('Single Room', 'Single Room'), ('Other', 'Other')], default='1BHK', help_text='Type of property', max_length=50),
        ),
    ]
