# Generated by Django 5.1.4 on 2025-01-27 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(max_length=20)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
            ],
        ),
    ]
