# Generated by Django 5.1.4 on 2025-01-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_model'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='houses.house'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.PositiveIntegerField()),
                ('balance_due', models.PositiveIntegerField(default=0)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('period', models.CharField(max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant')),
            ],
        ),
    ]
