# Generated by Django 5.1.4 on 2025-01-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_house_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance_due',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
