# Generated by Django 5.1.4 on 2025-01-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_payment_balance_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='overpayment',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
