# Generated by Django 5.1.4 on 2025-01-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_house_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.house'),
            preserve_default=False,
        ),
    ]
