# Generated by Django 5.1.4 on 2025-01-27 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_payment_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.house'),
        ),
    ]
