# Generated by Django 5.1.4 on 2025-01-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_payment_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.house'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
