# Generated by Django 5.1.4 on 2025-01-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_payment_house_delete_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='house',
        ),
    ]
