# Generated by Django 5.1.4 on 2025-01-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_payment_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='house',
        ),
    ]
