# Generated by Django 5.1.5 on 2025-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_charge_document_maintenancerequest_delete_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='national_id',
            field=models.CharField(help_text='National identification number', max_length=20),
        ),
    ]
